apiVersion: v1
kind: Service
metadata: 
  name: result
  labels: 
    name: result-service
    app: demo-result-app
spec:
  # since this service needs to be accessed by users so type is nodeport
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodeport: 30004
  selector:
    name: result-app-pod
    app: demo-voting-app
